name: shopping_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


flutter:
  uses-material-design: true

  assets:
    - assets/supermarket.jpg

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0  
  provider: ^6.1.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  permission_handler: ^11.0.1  
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.8
  firebase_database: ^10.5.7
  razorpay_flutter: ^1.4.0
  pdf: ^3.10.0 
  open_file: ^3.2.1 





